import './globals.css'
import { Poppins } from 'next/font/google'
import Providers from './utils/Providers'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Calender To-Do App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} min-h-screen place-content-center bg-bgContainer font-poppins md:grid md:bg-slate-600`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
