import "./globals.css";
import { Poppins } from "next/font/google";
import Providers from "./Providers";

const poppins = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-bgContainer md:bg-slate-600`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
